In [1]:
print("Ciao Mondo")

Ciao Mondo

In [2]:
import pandas as pd

# Creazione del dataframe(dati) = dataset(Tabella)
data = {
    "nome":["Filippo", "Salomon", "Asia", "Catalina", "Camilla", "Ana", "Giuseppe", "Melania", "Alessio", "Camilla", "Cristian","Mattia", "Moussa" ],
    "cognome": ["Battaglia", "Verdi", "Blu", "Birsan", "Noguti", "Bianchi", "Giallini", "Lucio", "Vianello", "Resto", "D'Avena","Torta", "Salisou"],
    "voto":[8,10,10,6,7,8,9,4,7,9,10,6,5]

}

df = pd.DataFrame(data)
# 1. "df =" 
# 2. "pd." 
# 3. "DataFrame" 
# 4. "(data)"

- Importa Pandas 
  - con alias pd (per facilitare la digitazione)
- primo passo con pandas
- creo un DataFrame ossia inserisco un dictionary, una lista o un tuple nominandolo (in questo caso ha nome "data")
  - dopo di che:
    - dichiaro  che df (nome del nostro dataframe) corrisponde (1.)
    - al DataFrame (3.)
    - con classe (argomento) chiamato "data" (nel nostro caso) (4.) 
    - attraverso pandas (2.)

In [3]:
df

        nome    cognome  voto
0    Filippo  Battaglia     8
1    Salomon      Verdi    10
2       Asia        Blu    10
3   Catalina     Birsan     6
4    Camilla     Noguti     7
5        Ana    Bianchi     8
6   Giuseppe   Giallini     9
7    Melania      Lucio     4
8    Alessio   Vianello     7
9    Camilla      Resto     9
10  Cristian    D'Avena    10
11    Mattia      Torta     6
12    Moussa    Salisou     5

stampa a schermo in formato tabella

In [16]:
print(df)

        nome    cognome  voto
0    Filippo  Battaglia     8
1    Salomon      Verdi    10
2       Asia        Blu    10
3   Catalina     Birsan     6
4    Camilla     Noguti     7
5        Ana    Bianchi     8
6   Giuseppe   Giallini     9
7    Melania      Lucio     4
8    Alessio   Vianello     7
9    Camilla      Resto     9
10  Cristian    D'Avena    10
11    Mattia      Torta     6
12    Moussa    Salisou     5

lo stampa a schermo uguale a un file CVS, ossia separato da virgole o spazi, senza formato

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     13 non-null     str
 1   cognome  13 non-null     str
 2   voto     13 non-null     int64
dtypes: int64(1), str(2)
memory usage: 444.0 bytes

mi da tutte le informazioni della tabella di pertinenza (in questo caso df)

In [11]:
df.head()

       nome    cognome  voto
0   Filippo  Battaglia     8
1   Salomon      Verdi    10
2      Asia        Blu    10
3  Catalina     Birsan     6
4   Camilla     Noguti     7

- mi restituisce solo le prime righe (come il SELECT TOP N Righe)
- fra parentesi posso indicare quante righe voglio stampare a schermo

In [12]:
df.describe()

            voto
count  13.000000
mean    7.615385
std     1.980676
min     4.000000
25%     6.000000
50%     8.000000
75%     9.000000
max    10.000000

restituisce le statistiche descrittive del dataframe (max, min, count, avg, ecc)

In [13]:
df["nome"]

0      Filippo
1      Salomon
2         Asia
3     Catalina
4      Camilla
5          Ana
6     Giuseppe
7      Melania
8      Alessio
9      Camilla
10    Cristian
11      Mattia
12      Moussa
Name: nome, dtype: str

restituisce la lista dei nomi

In [14]:
df[["nome", "voto"]]

        nome  voto
0    Filippo     8
1    Salomon    10
2       Asia    10
3   Catalina     6
4    Camilla     7
5        Ana     8
6   Giuseppe     9
7    Melania     4
8    Alessio     7
9    Camilla     9
10  Cristian    10
11    Mattia     6
12    Moussa     5

restituisce la lista dei nomi e i voti