In [1]:
import pandas as pd

# Creazione del dataframe(dati) = dataset(Tabella)
data = {
    "nome":["Filippo", "Salomon", "Asia", "Catalina", "Camilla", "Ana", "Giuseppe", "Melania", "Alessio", "Camilla", "Cristian","Mattia", "Moussa" ],
    "cognome": ["Battaglia", "Verdi", "Blu", "Birsan", "Noguti", "Bianchi", "Giallini", "Lucio", "Vianello", "Resto", "D'Avena","Torta", "Salisou"],
    "voto":[8,10,10,6,7,8,9,4,7,9,10,6,5]

}

df = pd.DataFrame(data)

df

        nome    cognome  voto
0    Filippo  Battaglia     8
1    Salomon      Verdi    10
2       Asia        Blu    10
3   Catalina     Birsan     6
4    Camilla     Noguti     7
5        Ana    Bianchi     8
6   Giuseppe   Giallini     9
7    Melania      Lucio     4
8    Alessio   Vianello     7
9    Camilla      Resto     9
10  Cristian    D'Avena    10
11    Mattia      Torta     6
12    Moussa    Salisou     5

In [4]:
df[df["voto"]>=7]

        nome    cognome  voto
0    Filippo  Battaglia     8
1    Salomon      Verdi    10
2       Asia        Blu    10
4    Camilla     Noguti     7
5        Ana    Bianchi     8
6   Giuseppe   Giallini     9
8    Alessio   Vianello     7
9    Camilla      Resto     9
10  Cristian    D'Avena    10

serve a filtrare i dati, in questo caso tutti gli studenti con un voto maggiore o uguale a 7

In [5]:
df["voto"].mean()

np.float64(7.615384615384615)

calcolo la media

In [7]:
df["Promosso"] = df["voto"] > 8
df

        nome    cognome  voto  Promosso
0    Filippo  Battaglia     8     False
1    Salomon      Verdi    10      True
2       Asia        Blu    10      True
3   Catalina     Birsan     6     False
4    Camilla     Noguti     7     False
5        Ana    Bianchi     8     False
6   Giuseppe   Giallini     9      True
7    Melania      Lucio     4     False
8    Alessio   Vianello     7     False
9    Camilla      Resto     9      True
10  Cristian    D'Avena    10      True
11    Mattia      Torta     6     False
12    Moussa    Salisou     5     False

Aggiorniamo la colonna con Promosso che restituirà True o False in base alla condizione (>8 in questo caso)

In [8]:
df.sort_values(by = "voto", ascending=False)

        nome    cognome  voto  Promosso
1    Salomon      Verdi    10      True
2       Asia        Blu    10      True
10  Cristian    D'Avena    10      True
6   Giuseppe   Giallini     9      True
9    Camilla      Resto     9      True
0    Filippo  Battaglia     8     False
5        Ana    Bianchi     8     False
4    Camilla     Noguti     7     False
8    Alessio   Vianello     7     False
3   Catalina     Birsan     6     False
11    Mattia      Torta     6     False
12    Moussa    Salisou     5     False
7    Melania      Lucio     4     False

Ordiniamo in maniera discendente (=False)

In [9]:
df.sort_values(by = "voto", ascending=True)

        nome    cognome  voto  Promosso
7    Melania      Lucio     4     False
12    Moussa    Salisou     5     False
3   Catalina     Birsan     6     False
11    Mattia      Torta     6     False
4    Camilla     Noguti     7     False
8    Alessio   Vianello     7     False
0    Filippo  Battaglia     8     False
5        Ana    Bianchi     8     False
6   Giuseppe   Giallini     9      True
9    Camilla      Resto     9      True
1    Salomon      Verdi    10      True
2       Asia        Blu    10      True
10  Cristian    D'Avena    10      True

Ordiniamo in maniera ascendente (=True) perchè lo è di default (non esiste descending)

In [10]:
df.sort_values(by = "voto", ascending=True, inplace=True)

- null = inplace True
- not null = inplace False
- non è obbligatorio inserirlo nel primo
- ma è fondamentale nel secondo